"""initial schema

Revision ID: 0ecdb22b199e
Revises: 
Create Date: 2026-09-16 08:10:38.374524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ecdb22b199e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('org_code', sa.String(length=50), nullable=False),
    sa.Column('rep_email', sa.String(length=200), nullable=False),
    sa.Column('vice_rep_email', sa.String(length=200), nullable=False),
    sa.Column('advisor_email', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_code')
    )
    op.create_table('activity_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('participants_count', sa.Integer(), nullable=False),
    sa.Column('leader_name', sa.String(length=100), nullable=False),
    sa.Column('leader_phone', sa.String(length=50), nullable=False),
    sa.Column('leader_email', sa.String(length=200), nullable=False),
    sa.Column('requires_precheck', sa.Boolean(), nullable=False),
    sa.Column('itinerary_summary', sa.Text(), nullable=False),
    sa.Column('declared_itinerary', sa.Boolean(), nullable=False),
    sa.Column('notes_to_university', sa.Text(), nullable=False),
    sa.Column('application_no', sa.String(length=30), nullable=False),
    sa.Column('org_code', sa.String(length=50), nullable=False),
    sa.Column('applicant_name', sa.String(length=100), nullable=False),
    sa.Column('applicant_email', sa.String(length=200), nullable=False),
    sa.Column('applicant_check', sa.Enum('MATCH', 'NEEDS_REVIEW', 'UNVERIFIABLE', name='applicantcheck'), nullable=False),
    sa.Column('status', sa.Enum('UNCONFIRMED', 'CONFIRMED', 'RETURNED', 'CANCELLED', 'COMPLETED', name='reportstatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('missing_items', sa.Text(), nullable=False),
    sa.Column('last_notified_status', sa.String(length=20), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_no')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('student_no', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('registered_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'fiscal_year', 'student_no', name='uq_member')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('ITINERARY', 'OTHER', name='attachmentkind'), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['activity_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('actor_email', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['activity_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('to_email', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['activity_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('student_no', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['activity_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participants')
    op.drop_table('notifications')
    op.drop_table('audit_logs')
    op.drop_table('attachments')
    op.drop_table('members')
    op.drop_table('activity_reports')
    op.drop_table('organizations')
    # ### end Alembic commands ###
